version: "3"
services:
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"  #set heap memory here
      discovery.type: single-node
      ELASTIC_PASSWORD: PleaseChangeMe@1!
      KEYSTORE_PASSWORD: PleaseChangeMe@1!
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    restart: always
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.13.0
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.13.0
    ports:
      - 8200:8200
    command: >
      apm-server -e
        -E setup.template.settings.index.number_of_replicas=0
        -E monitoring.enabled=true
        -E apm-server.expvar.enabled=true
        -E apm-server.ilm.enabled=false
        -E apm-server.instrumentation.enabled=true
        -E output.elasticsearch.hosts=['http://elasticsearch:9200']
        -E output.elasticsearch.username="elastic"
        -E output.elasticsearch.password="PleaseChangeMe@1!"
    environment: 
    -  output.elasticsearch.hosts=['http://elasticsearch:9200']
    -  output.elasticsearch.username="elastic"
    -  output.elasticsearch.password="PleaseChangeMe@1!"
    -  apm-server.host="0.0.0.0:8200"
    -  apm-server.secret_token="xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44"
    -  setup.kibana.host="kibana:5601"
    -  setup.kibana.password="elastic"
    -  setup.kibana.host="PleaseChangeMe@1!"
    -  setup.template.enabled=true
    -  logging.to_files=false
    depends_on:
      - elasticsearch
      - kibana

volumes:
  elasticsearchdata:
